In [1]:
import numpy as np

In [2]:
#zeros/ones
np.zeros(3,)

array([0., 0., 0.])

In [12]:
a = np.zeros([3,3,3])

In [13]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
a.ndim

3

In [15]:
#ones
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
x = np.ones([5,3,2])

In [20]:
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
x.ndim

3

In [22]:
#Wap to add 2 list
a = [1,2,3]
b=[3,4,5]
c=a+b
c

[1, 2, 3, 3, 4, 5]

In [23]:
# Number of axis

a=np.array([[1,2,3],[3,4,5]])

In [24]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [25]:
a.sum()

18

In [26]:
a.sum(axis=0)

array([4, 6, 8])

In [27]:
a.sum(axis=1)

array([ 6, 12])

In [28]:
a.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [31]:
x = np.array([[[1,2,3],[3,4,5],[5,6,7]]])

In [32]:
x

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [34]:
x.sum(axis=0)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [35]:
x.sum(axis=1)

array([[ 9, 12, 15]])

In [36]:
x.sum(axis=2)

array([[ 6, 12, 18]])

In [37]:
# +,-,*,/
x.sum()

36

In [41]:
x= np.array([[1,2,3],[98,76,23]])

In [42]:
x

array([[ 1,  2,  3],
       [98, 76, 23]])

In [43]:
#transpose matrix
x.T

array([[ 1, 98],
       [ 2, 76],
       [ 3, 23]])

In [44]:
#searching / sorting
a = np.array([100,30,89,34,67,23,12,28,32])

In [45]:
a

array([100,  30,  89,  34,  67,  23,  12,  28,  32])

In [46]:
#search
np.where(a%2==0)

(array([0, 1, 3, 6, 7, 8], dtype=int64),)

In [47]:
# sorting
a

array([100,  30,  89,  34,  67,  23,  12,  28,  32])

In [48]:
a.sort()

In [49]:
a

array([ 12,  23,  28,  30,  32,  34,  67,  89, 100])

In [51]:
# plz don't use this code in future for printing the descending order of data
a.sort(-1)

In [52]:
a

array([ 12,  23,  28,  30,  32,  34,  67,  89, 100])

In [53]:
a =  np.array([100,30,89,34,67,23,12,28,32])

In [54]:
a.sort(-1)

In [55]:
a

array([ 12,  23,  28,  30,  32,  34,  67,  89, 100])

In [63]:
# min/max/mean,median,mode
a = np.array([[100,30,89,34,67,10],[10,23,12,28,32,890]])

In [64]:
a

array([[100,  30,  89,  34,  67,  10],
       [ 10,  23,  12,  28,  32, 890]])

In [65]:
# min
a.min()

10

In [66]:
a.max()

890

In [67]:
a.mean()

110.41666666666667

In [69]:
a.median

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [70]:
a.mode()

AttributeError: 'numpy.ndarray' object has no attribute 'mode'

In [71]:
# Argmax
# argmin
# argsort

x = np.array([[[120,34,23],[990,78,5555],[221,890,6675]]])

In [72]:
x

array([[[ 120,   34,   23],
        [ 990,   78, 5555],
        [ 221,  890, 6675]]])

In [73]:
x.argmax()

8

In [74]:
x.argmin()

2

In [75]:
x.argsort()

array([[[2, 1, 0],
        [1, 0, 2],
        [0, 1, 2]]], dtype=int64)