In [2]:
#numpy----- array
import numpy as np

In [5]:
#array----->
a = np.array([1,2,4,6,8,9])
a


array([1, 2, 4, 6, 8, 9])

In [6]:
#type function
type(a)

numpy.ndarray

In [7]:
#ndim
a.ndim

1

In [8]:
#Shape & size
a

array([1, 2, 4, 6, 8, 9])

In [9]:
a.shape

(6,)

In [10]:
a.size

6

In [11]:
#2d data
a

array([1, 2, 4, 6, 8, 9])

In [14]:
x = np.array([[1, 2, 4, 6, 8, 9]])

In [15]:
x

array([[1, 2, 4, 6, 8, 9]])

In [16]:
x.shape

(1, 6)

In [17]:
x.ndim

2

In [18]:
s = np.array([[1,2,3],[7,8,9]])
s

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
s.shape

(2, 3)

In [20]:
s = np.array([[1,2,3],[7,8]])
s

C:\Users\Satyam\AppData\Local\Temp/ipykernel_8676/2500512350.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  s = np.array([[1,2,3],[7,8]])


array([list([1, 2, 3]), list([7, 8])], dtype=object)

In [21]:
#check the data type of the array
type(s)

numpy.ndarray

In [22]:
s.dtype

dtype('O')

In [23]:
#3d data
a = np.array([[1,2,3],[7,8,9]])

In [24]:
a

array([[1, 2, 3],
       [7, 8, 9]])

In [25]:
a.ndim

2

In [26]:
a.dtype

dtype('int32')

In [27]:
#3d data
w = np.array([[[1,2,3]]])

In [28]:
w

array([[[1, 2, 3]]])

In [29]:
w.ndim

3

In [30]:
w.shape

(1, 1, 3)

In [31]:
w.size

3

In [32]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [33]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [34]:
a.ndim

3

In [35]:
a.shape

(1, 3, 3)

In [36]:
a.size

9

In [41]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4]]])

C:\Users\Satyam\AppData\Local\Temp/ipykernel_8676/3906923036.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4]]])


In [42]:
a

array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), list([[2, 3, 4]])],
      dtype=object)

In [43]:
a.shape

(2,)

In [45]:
a = np.array([[[1, 2, 3],[1, 2, 3]],[[1, 2, 3],[1, 2 ,3]]])

In [46]:
a

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [47]:
a.shape

(2, 2, 3)

In [48]:
a = np.array([[1,2,3],[45,78,90]])

In [49]:
a

array([[ 1,  2,  3],
       [45, 78, 90]])

In [52]:
#wap and slice with the help of index to the data i.e 45.
a[1][0]

45

In [59]:
# numpy----> zeroes
np.zeros(40)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [60]:
#ones 
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(20,300,90)

array([ 20, 110, 200, 290])